title: ppts document
description: Structured content preparation and typesetting API documentation for ppts
theme: just-the-docs

url: https://pptypeset.github.io/doc-en

aux_links:
  New issue or request: https://github.com/pptypeset/doc-en/issues
